# Generated by Django 5.1.3 on 2024-12-03 11:04

import dashboard.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='name',
        ),
        migrations.RemoveField(
            model_name='message',
            name='score',
        ),
        migrations.AddField(
            model_name='message',
            name='event_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='message',
            name='event_name',
            field=models.CharField(default='Default Event', max_length=100),
        ),
        migrations.AddField(
            model_name='message',
            name='event_time',
            field=models.TimeField(default=dashboard.models.get_current_time),
        ),
        migrations.AddField(
            model_name='message',
            name='team_name',
            field=models.CharField(default='Default Team', max_length=100),
        ),
    ]
